// NOTE: Hub routes have been consolidated into storyRoutes.js.
// This file is kept for reference but is NOT mounted in server.js.
// All hub endpoints are available under /api/stories/:storyId/hub/...
